vich_uploader:
    db_driver: orm

    mappings:
        post:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/assets/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
