# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_image:
            uri_prefix: /images/cours
            upload_destination: '%kernel.project_dir%/public/images/cours'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_program:
            uri_prefix: /programs
            upload_destination: '%kernel.project_dir%/public/programs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer